package com.jcloisterzone.game;

public enum ReturnMeepleSource {
	PRINCESS,
	SIEGE_ESCAPE,
	FESTIVAL,
	CORN_CIRCLE,
	ABBOT_RETURN,
	MONASTERY_SHRINE_CHALLENGE,
	BARN_PLACEMENT,
	BARN_FIELD_JOIN,
	TRAP,
	ROBBERS_SON
}
